### ISSUE TITLE
Token field may not be send in server-notification

### ISSUE THREAD

**Issue by Patabugen** [academe/SagePay#15]
Unless you request it and enable (and pay for) it on your account you don't generate 'Token' emails.

Server.php around line 240 has this line:
```
$this->setField('Token', $post['Token']);
```

which throws an error if Surcharge isn't sent.

For now I've just done
```
if (isset($post['Token'])) {
    $this->setField('Token', $post['Token']);
}
```

**Comment by judgej** [comment]
I'm assuming the last change fixed this. Pleas reopen if I'm mistaken.
