### ISSUE TITLE
Helper::formatAmount silently sets Amount to Zero

### ISSUE THREAD

**Issue by Patabugen** [academe/SagePay#16]
```
$server->setAmount('1,234.56', 'GBP');
echo $server->getField('Amount'); // Returns numeric 0
```
because of

`if ( ! is_numeric($amount)) $amount = 0;`

I'd reckon it should return something non-numeric at least, but I'd suggest it throws an exceptions since that number should be checked elsewhere.

**Comment by judgej** [comment]
Looking at this further, I cannot find any payment gateways or accountancy packages that use commas for the decimal separator. PHP uses the full stop or period (.) in all its numeric operations. Numbers are always represented as decimals like this (e.g. 1.23). Like most - or all - PHP payment gateways, we are going to enforce that kind of decimal point, with optional comma (,) thousands separators, if passed in as a string.

**Comment by judgej** [comment]
Ideally we would use currency and amount objects to handle the amount. The [successor to this package](https://github.com/academe/SagePay-Integration) does. For now, I've put a validation check in the point where the currency is formatted. If passed in as a string, the format must adhere to:

* Always start with a digit (not "," or ".")
* Use a single but optional decimal point (.)
* The decimal digits must not exceed the minor units for the currency. So GDP 1.00 is allowed, but GDP 1.000 is not, even if they have the same decimal value.
* Optional thousands separators use the comma (,)
