### ISSUE TITLE
Support 3d Secure v2

### ISSUE THREAD

**Issue by Patabugen** [academe/SagePay#40]
3D Secure v2 has been announced and will be mandatory from the end of 2020.

We have a bit of time :)

Do you have any plans to test/update the library for it?

If not - I'm happy to look into it or work with you on it. Thought I'd check before potentially duplicating work.

SagePay's (fairly basic) details:
https://www.sagepay.co.uk/support/12/36/3d-secure-explained

**Comment by judgej** [comment]
I've got no real plans with this package, as I'm more focused on the Omnipay APIs for Sagepay. I'm happy to accept PRs though, and will help where I can (though have limited time).

**Comment by Patabugen** [comment]
No worries!

I've just spoken to SagePay who have confirmed that it's only people using the Direct integration who need to do anything.

Since your library only support Server integration - no action needs to be done.

Therefore this is already 3D Secure v3 compatible. #winning

**Comment by judgej** [comment]
That's the kind of development work we like! Thank you for checking :-)

**Comment by Patabugen** [comment]
In case anyone else reads this and wonders (and correct me if I'm wrong) Omnipay is totally different from what this library does.

I wondered if it was the next way of doing the same thing (and whether I should consider migrating) - but (talking to Sage) it's just a different thing taking up @judgej's time  :)

**Comment by judgej** [comment]
I wrote this long before Omnipay, soon after Sage had bought Protx to re-badge as Sage Pay.
